Repository stormyy00/cutiehack2024, pull requests merged in 2024-10, with the labels that each got.

#9 added assets, added font
  public/assets/astronauthappy.svg
  public/assets/astronautvibe.svg
  public/assets/blueflag.svg
  public/assets/cutiehackLOGO.svg
  public/assets/galaxyorange.svg
  public/assets/galaxypurple.svg
  public/assets/greyflag.svg
  public/assets/moon.svg
  public/assets/rocketbubble.svg
  public/assets/rocketship.svg
  public/assets/satellite.svg
  public/assets/star.svg
  public/assets/starwhite.svg
  public/assets/staryellow.svg
  public/assets/ufo.svg
  public/assets/window.svg
  src/app/layout.tsx
  tailwind.config.js
Labels: Ready to Review

#12 added navbar couldn't find font-family
  src/components/live/Landing.jsx
  src/components/live/Live.jsx
  src/components/live/Navigation.jsx
  src/data/live/Navigation.js
  tailwind.config.js
Labels: Ready to Review

#10 Landing and About components
  README.md
  public/assets/cutieLogo.svg
  public/assets/edgebubble.svg
  public/assets/rocketship.svg
  src/components/live/About.jsx
  src/components/live/Apply.jsx
  src/components/live/Countdown.jsx
  src/components/live/Landing.jsx
  src/components/live/Navigation.jsx
  src/data/Config.ts
Labels: Ready to Review

#19 Updated User Dashboard
  src/components/Navigation.jsx
  src/components/ProtectedPage.jsx
  src/components/user/BulletList.jsx
  src/components/user/CheckIn.jsx
  src/components/user/Countdown.jsx
  src/components/user/Dashboard.jsx
  src/components/user/Header.tsx
  src/components/user/Packing.tsx
  src/components/user/Resources.tsx
  src/components/user/Rooms.tsx
  src/components/user/Tile.jsx
  src/components/user/schedule/Events.jsx
  src/components/user/schedule/Schedule.jsx
  src/components/user/schedule/Toolbar.jsx
  tsconfig.json
Labels: Ready to Review

#23 Styled FAQ
  src/components/live/faq/FAQ.tsx
  src/components/live/faq/Item.tsx
  src/data/FAQ.ts
Labels: Ready to Review

#22 footer
  public/assets/cutiehackflag.svg
  public/assets/moon.svg
  src/components/live/Footer.jsx
Labels: Ready to Review

#25 fix responsivenes and animation
  src/components/live/Footer.jsx
  src/components/live/Footer.tsx
  src/components/live/faq/FAQ.tsx
  tailwind.config.js
Labels: Ready to Review

#31 fixed icon links
  src/components/live/Footer.tsx
Labels: Ready to Review

#30 forms semi good
  cypress/component/Checkbox.cy.jsx
  cypress/component/Loading.cy.jsx
  src/components/Checkbox.tsx
  src/components/Input.jsx
  src/components/Loading.tsx
  src/components/Select.jsx
  src/components/form/form/Form.jsx
  src/components/form/form/Questions.jsx
  src/components/form/form/Status.jsx
  src/components/form/form/Upload.jsx
  src/components/ui/radio-group.tsx
  src/data/Button.js
  tailwind.config.js
Labels: Ready to Review

#20 Team Component
  package-lock.json
  package.json
  public/assets/window.svg
  public/board/allison2024.webp
  public/board/jonathan2024.webp
  public/board/taaha2024.webp
  src/components/live/Committees.jsx
  src/components/live/Live.jsx
  src/components/live/Team.jsx
  src/components/live/leads/Committees.jsx
  src/components/live/leads/Header.jsx
  src/components/live/leads/Profile.jsx
  src/components/live/leads/Team.jsx
  src/data/live/Team.js
Labels: Ready to Review

#32 Holland pleskac/sponsors
  public/assets/sponsors/cooler-master.svg
  public/assets/sponsors/index.js
  public/assets/sponsors/ring-left.svg
  public/assets/sponsors/ring-right.svg
  public/assets/sponsors/sponsor-flag.svg
  public/assets/sponsors/sponsor-small.svg
  src/components/live/Sponsors.jsx
Labels: enhancement, Ready to Review

#18 created title
  public/assets/whitestar.svg
  src/components/live/Judges.jsx
  src/components/live/Sponsors.jsx
  src/components/live/Title.jsx
  src/components/live/leads/Committees.jsx
  src/components/live/leads/Profile.jsx
  src/data/live/Judges.js
  tsconfig.json
Labels: Ready to Review

#36 Change logo on Portal navbar
  src/components/Navigation.jsx
Labels: good first issue

#35 added styles
  src/components/Select.jsx
  src/components/admin/Input.jsx
  src/components/admin/Title.tsx
  src/components/admin/dashboards/dashboard/Body.jsx
  src/components/admin/dashboards/dashboard/Filters.jsx
  src/components/admin/dashboards/dashboard/Table.jsx
  src/components/admin/dashboards/dashboard/Toolbar.jsx
Labels: Ready to Review

#49 Implement React Scroll
  package-lock.json
  package.json
  src/components/live/About.tsx
  src/components/live/Apply.tsx
  src/components/live/Landing.tsx
  src/components/live/Live.jsx
  src/components/live/Navigation.tsx
  src/components/live/schedule/Schedule.jsx
  src/data/live/Navigation.js
Labels: Ready to Review

#50 added stats
  cypress/component/Loading.cy.jsx
  src/components/Loading.tsx
  src/components/Select.jsx
  src/components/admin/Input.jsx
  src/components/admin/dashboards/dashboard/Body.jsx
  src/components/admin/dashboards/dashboard/Table.jsx
  src/components/email/Template.jsx
  src/components/form/form/Upload.jsx
  src/components/live/About.tsx
  src/components/live/Footer.tsx
  src/components/live/Live.jsx
  src/components/live/Navigation.tsx
  src/data/Button.js
  src/data/Config.ts
  src/data/live/Navigation.js
  src/data/live/Stats.js
  tailwind.config.js
Labels: Ready to Review
